services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://Bhatt:bhatt123@mongodb:27017/file-tracking-dev?authSource=file-tracking-dev 
     # - MONGODB_URI=mongodb://filetrackinguser:filetrackingpassword@mongodb:27017/file-tracking-dev
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
      - ALLOWED_FILE_TYPES="image/png,image/jpeg,image/jpg,image/gif,image/webp,image/bmp,image/svg+xml,image/tiff,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,application/rtf,video/mp4,video/mpeg,video/quicktime,video/x-msvideo,video/x-ms-wmv,video/webm,video/3gpp,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,application/zip,application/x-rar-compressed,application/x-7z-compressed,application/x-tar,application/gzip,application/octet-stream"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
    networks:
      - file-tracking-network

  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=file-tracking-dev
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - file-tracking-network

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      # Secure dashboard with Basic Auth
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=strongpassword123
    depends_on:
      - mongodb
    networks:
      - file-tracking-network

volumes:
  mongodb_data:

networks:
  file-tracking-network:
    driver: bridge
